auth_enabled: false 

server:   
  http_listen_port: 3100 

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1   
      heartbeat_timeout: 1m 
   # *** TAMBAHAN PENTING INI ***   
  wal:     
    dir: /tmp/loki/wal # Tentukan direktori WAL di sini 

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:   
  filesystem:
    directory: /tmp/loki/chunks 
  boltdb_shipper: 
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    resync_interval: 5m

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor

limits_config:
  allow_structured_metadata: false 

table_manager:
  retention_deletes_enabled: true 
  retention_period: 1d 


