# Generated by Django 5.2.4 on 2025-07-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='stok_minimum',
            field=models.IntegerField(default=10, help_text='Batas stok minimum untuk notifikasi'),
        ),
    ]
