# Generated by Django 5.2.4 on 2025-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_barang_sku_barang_stok_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='harga_saat_transaksi',
            field=models.FloatField(blank=True, help_text='Harga satuan barang pada saat transaksi', null=True),
        ),
    ]
