name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.18]

    steps:
    - uses: actions/checkout@v4
     # ================== LANGKAH DEBUG BARU ==================
    - name: Debug File Content
      run: |
        echo "Mencetak isi file workflow untuk debug:"
        cat .github/workflows/django.yml
      # ========================================================
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env          
    - name: Run Tests
      run: |
        python manage.py test
    - name: SonarCloud Scan
      with:
        args: >
          -Dsonar.organization=rahmatsuhadi 
          -Dsonar.projectKey=rahmatsuhadi_fp-inventaris-gudang
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.test.exclusions=tests/**
          -Dsonar.verbose=true
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: "rahmatsuhadi_fp-inventaris-gudang"
        SONAR_ORGANIZATION: "rahmatsuhadi"
      
      
        
